<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="AvailableMarginSend" targetNamespace="http://www.kpei.co.id/service/AvailableMarginSend" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:inp1="http://www.kpei.co.id/schema/AvailableMargin" xmlns:tns="http://www.kpei.co.id/service/AvailableMarginSend">
   <wsdl:types>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://www.kpei.co.id/schema/AvailableMargin" schemaLocation="xsd/AvailableMargin.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="requestMessage">
      <wsdl:part name="request" element="inp1:AvailableMargin"/>
   </wsdl:message>
   <wsdl:portType name="execute_ptt">
      <wsdl:operation name="send">
         <wsdl:input message="tns:requestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
