<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="eCLEARS_TradingLimit" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ARIS-KPEI-PROJECT/OR20-RAZORTradingLimit/eCLEARS_TradingLimit" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/ARIS-KPEI-PROJECT/OR20-RAZORTradingLimit/eCLEARS_TradingLimit" xmlns:imp1="http://www.kpei.co.id/middleware/outbound/tradingLimit" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <plt:partnerLinkType name="sendToEclearsTradingLimit_plt">
      <plt:role name="sendToEclearsTradingLimit_role">
         <plt:portType name="tns:sendToEclearsTradingLimit_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.kpei.co.id/middleware/outbound/tradingLimit" schemaLocation="xsd/tradingLimit-response.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="sendToEclearsTradingLimit_msg">
      <wsdl:part name="body" element="imp1:kpeiOutbound"/>
   </wsdl:message>
   <wsdl:portType name="sendToEclearsTradingLimit_ptt">
      <wsdl:operation name="sendToEclearsTradingLimit">
         <wsdl:input message="tns:sendToEclearsTradingLimit_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
