<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://www.kpei.co.id/MemberInterface" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:tns="http://www.kpei.co.id/MemberInterface" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <plnk:partnerLinkType name="mi_ws">
      <plnk:role name="MemberInterfaceServicesSoap">
         <plnk:portType name="tns:MemberInterfaceServicesSoap"/>
      </plnk:role>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://www.kpei.co.id/MemberInterface" location="http://serviceserver:7777/soa-infra/services/MWII/MIServices/MIServices.wsdl"/>
</wsdl:definitions>
