<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="eCLEARS_freeCollateral_write" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ARIS-KPEI-PROJECT/OR17-RAZORFreeCollateral/eCLEARS_freeCollateral_write" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/ARIS-KPEI-PROJECT/OR17-RAZORFreeCollateral/eCLEARS_freeCollateral_write" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:imp1="http://www.kpei.co.id/middleware/outbound/freeCollateral" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <plt:partnerLinkType name="sendMessage_FreeCollateral_eCLEARS_plt">
      <plt:role name="sendMessage-FreeCollateral-eCLEARS_role">
         <plt:portType name="tns:sendMessage_FreeCollateral_eCLEARS_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.kpei.co.id/middleware/outbound/freeCollateral" schemaLocation="xsd/freeCollateral-outbound.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="sendMessage-FreeCollateral-eCLEARS_msg">
      <wsdl:part name="body" element="imp1:kpeiOutbound"/>
   </wsdl:message>
   <wsdl:portType name="sendMessage_FreeCollateral_eCLEARS_ptt">
      <wsdl:operation name="sendMessage-FreeCollateral-eCLEARS">
         <wsdl:input message="tns:sendMessage-FreeCollateral-eCLEARS_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
