<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="messageMonitorService" targetNamespace="http://oracle.com/sca/soapservice/KPEI-MIDDLEWARE/Ge01-messageMonitor/messageMonitorService" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:tns="http://oracle.com/sca/soapservice/KPEI-MIDDLEWARE/Ge01-messageMonitor/messageMonitorService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <plnk:partnerLinkType name="GE01-MessageMonitor">
      <plnk:role name="messageMonitor">
         <plnk:portType name="tns:messageMonitor"/>
      </plnk:role>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://oracle.com/sca/soapservice/KPEI-MIDDLEWARE/Ge01-messageMonitor/messageMonitorService" location="http://SERVICESERVER:7777/soa-infra/services/default/GE01-MessageMonitor/GE01-MessageMonitor?WSDL"/>
</wsdl:definitions>
