<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://www.kpei.co.id/GE02-FileUtility" xmlns:ns1="http://www.kpei.co.id/GE02-FileUtility" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <plnk:partnerLinkType name="GE02-FileUtility">
      <plnk:role name="GE02-FileUtility">
         <plnk:portType name="ns1:GE02-FileUtility"/>
      </plnk:role>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://www.kpei.co.id/GE02-FileUtility" location="http://SERVICESERVER:8001/kpei/GE02-FileUtility?wsdl"/>
</wsdl:definitions>
